PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?subject ?object WHERE {

	?subject <@property@> ?object .
	?subject rdf:type <@subjectType@> .
	
	FILTER(isLITERAL(?object)) .
	FILTER(DATATYPE(?object) = <@objectType@>) .
	
}