prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>

SELECT ?class (COUNT(DISTINCT(?i)) AS ?cnt)  {
	?i rdf:type ?class .
	FILTER(?class != owl:NamedIndividual) .
} GROUP BY ?class