SELECT ?dataset ?distribution ?datasetTitle ?distributionTitle ?size ?url ?datasetDescription ?distributionDescription ?distributionMediaType
FROM <https://data.wu.ac.at/portalwatch/ld/2002>

WHERE {
	?dataset a dcat:Dataset.
	?dataset dcat:distribution ?distribution .

	?distribution dct:format ?format .
	?format rdfs:label "@format@" .
	
	?distribution dcat:accessURL ?url .
	
	?distribution dct:title ?distributionTitle .
	OPTIONAL { ?distribution dct:description ?distributionDescription } .
	OPTIONAL { ?distribution dcat:byteSize ?size } . 
	OPTIONAL { ?distribution dcat:mediaType ?distributionMediaType } .
	
	OPTIONAL { ?dataset dct:title ?datasetTitle } .
	OPTIONAL { ?dataset dct:description ?datasetDescription } .
} GROUP BY ?dataset
